-- Schema base di S.A.G.E.
-- Questa e' la versione pulita per MySQL: tipi sistemati, chiavi esterne
-- esplicite e controlli CHECK dove servono.
-- Mantengo il nome TRANSIZIONE per restare coerente con gli altri script del
-- progetto, anche se semanticamente rappresenta sia spese sia entrate.

DROP DATABASE IF EXISTS Schema_finale_del_relazionale_SAGE_Vista_ibrida_Raffinata;
CREATE DATABASE Schema_finale_del_relazionale_SAGE_Vista_ibrida_Raffinata;
USE Schema_finale_del_relazionale_SAGE_Vista_ibrida_Raffinata;

CREATE TABLE UTENTE (
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(128) NOT NULL,
    Nome VARCHAR(80) NOT NULL,
    Cognome VARCHAR(80) NOT NULL,
    Ruolo VARCHAR(10) NOT NULL DEFAULT 'UTENTE',
    CONSTRAINT PK_UTENTE PRIMARY KEY (Email),
    CONSTRAINT CK_UTENTE_RUOLO CHECK (Ruolo IN ('UTENTE', 'ADMIN'))
);

CREATE TABLE PERIODO (
    ID_Periodo INT NOT NULL AUTO_INCREMENT,
    Mese TINYINT NOT NULL,
    Anno SMALLINT NOT NULL,
    CONSTRAINT PK_PERIODO PRIMARY KEY (ID_Periodo),
    CONSTRAINT UQ_PERIODO_MESE_ANNO UNIQUE (Mese, Anno),
    CONSTRAINT CK_PERIODO_MESE CHECK (Mese BETWEEN 1 AND 12),
    CONSTRAINT CK_PERIODO_ANNO CHECK (Anno >= 2000)
);

CREATE TABLE CATEGORIA (
    ID_Categoria INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(80) NOT NULL,
    Icona VARCHAR(255),
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    Email_Proprietario VARCHAR(255),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_Categoria),
    CONSTRAINT FK_CATEGORIA_UTENTE FOREIGN KEY (Email_Proprietario)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_CATEGORIA_OWNER CHECK (
        (is_system = TRUE AND Email_Proprietario IS NULL)
        OR
        (is_system = FALSE AND Email_Proprietario IS NOT NULL)
    )
);

CREATE TABLE FONTE (
    ID_Fonte INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(80) NOT NULL,
    Icona VARCHAR(255),
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    Email_Proprietario VARCHAR(255),
    CONSTRAINT PK_FONTE PRIMARY KEY (ID_Fonte),
    CONSTRAINT FK_FONTE_UTENTE FOREIGN KEY (Email_Proprietario)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_FONTE_OWNER CHECK (
        (is_system = TRUE AND Email_Proprietario IS NULL)
        OR
        (is_system = FALSE AND Email_Proprietario IS NOT NULL)
    )
);

CREATE TABLE TAG (
    ID_Tag INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(80) NOT NULL,
    Icona VARCHAR(255),
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    Email_Proprietario VARCHAR(255),
    CONSTRAINT PK_TAG PRIMARY KEY (ID_Tag),
    CONSTRAINT FK_TAG_UTENTE FOREIGN KEY (Email_Proprietario)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_TAG_OWNER CHECK (
        (is_system = TRUE AND Email_Proprietario IS NULL)
        OR
        (is_system = FALSE AND Email_Proprietario IS NOT NULL)
    )
);

CREATE TABLE BUDGET (
    ID_Budget INT NOT NULL AUTO_INCREMENT,
    Importo_Limite DECIMAL(10,2) NOT NULL,
    Alert_Soglia BOOLEAN NOT NULL DEFAULT TRUE,
    Totale_Speso_Attuale DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_Periodo INT NOT NULL,
    ID_Categoria INT,
    ID_Categoria_Key INT GENERATED ALWAYS AS (IFNULL(ID_Categoria, 0)) STORED,
    Email VARCHAR(255) NOT NULL,
    CONSTRAINT PK_BUDGET PRIMARY KEY (ID_Budget),
    CONSTRAINT FK_BUDGET_PERIODO FOREIGN KEY (ID_Periodo)
        REFERENCES PERIODO (ID_Periodo)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_BUDGET_CATEGORIA FOREIGN KEY (ID_Categoria)
        REFERENCES CATEGORIA (ID_Categoria)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT FK_BUDGET_UTENTE FOREIGN KEY (Email)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_BUDGET_IMPORTO CHECK (Importo_Limite >= 0),
    CONSTRAINT CK_BUDGET_TOTALE CHECK (Totale_Speso_Attuale >= 0),
    CONSTRAINT UQ_BUDGET_AMBITO UNIQUE (Email, ID_Periodo, ID_Categoria_Key)
);

CREATE TABLE TRANSIZIONE (
    ID_Transizione INT NOT NULL AUTO_INCREMENT,
    TipoTransazione CHAR(1) NOT NULL,
    Importo DECIMAL(10,2) NOT NULL,
    Data DATE NOT NULL,
    Descrizione VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    ID_Categoria INT,
    ID_Periodo INT NOT NULL,
    ID_Fonte INT,
    ID_Ricorrenza INT,
    CONSTRAINT PK_TRANSIZIONE PRIMARY KEY (ID_Transizione),
    CONSTRAINT FK_TRANSIZIONE_UTENTE FOREIGN KEY (Email)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_TRANSIZIONE_CATEGORIA FOREIGN KEY (ID_Categoria)
        REFERENCES CATEGORIA (ID_Categoria)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT FK_TRANSIZIONE_PERIODO FOREIGN KEY (ID_Periodo)
        REFERENCES PERIODO (ID_Periodo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_TRANSIZIONE_FONTE FOREIGN KEY (ID_Fonte)
        REFERENCES FONTE (ID_Fonte)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CK_TRANSIZIONE_TIPO CHECK (TipoTransazione IN ('S', 'E')),
    CONSTRAINT CK_TRANSIZIONE_IMPORTO CHECK (Importo > 0),
    CONSTRAINT CK_TRANSIZIONE_RICORRENZA CHECK (
        ID_Ricorrenza IS NULL OR TipoTransazione = 'S'
    ),
    CONSTRAINT CK_TRANSIZIONE_COLLASSO CHECK (
        (TipoTransazione = 'S' AND ID_Categoria IS NOT NULL AND ID_Fonte IS NULL)
        OR
        (TipoTransazione = 'E' AND ID_Categoria IS NULL AND ID_Fonte IS NOT NULL)
    )
);

CREATE TABLE SPESA_TAG (
    ID_Transizione INT NOT NULL,
    ID_Tag INT NOT NULL,
    CONSTRAINT PK_SPESA_TAG PRIMARY KEY (ID_Transizione, ID_Tag),
    CONSTRAINT FK_SPESA_TAG_TRANSIZIONE FOREIGN KEY (ID_Transizione)
        REFERENCES TRANSIZIONE (ID_Transizione)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_SPESA_TAG_TAG FOREIGN KEY (ID_Tag)
        REFERENCES TAG (ID_Tag)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE DOCUMENTO (
    ID_Documento INT NOT NULL AUTO_INCREMENT,
    ID_Transizione INT NOT NULL,
    Path_File VARCHAR(500) NOT NULL,
    Tipo_File VARCHAR(20) NOT NULL,
    Data_Acquisizione_Documento DATE NOT NULL,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID_Documento),
    CONSTRAINT FK_DOCUMENTO_TRANSIZIONE FOREIGN KEY (ID_Transizione)
        REFERENCES TRANSIZIONE (ID_Transizione)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE SPESA_RICORRENTE (
    ID_Ricorrenza INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Importo_Previsto DECIMAL(10,2) NOT NULL,
    Frequenza_Giorni INT NOT NULL,
    Data_Inizio DATE NOT NULL,
    Data_Prossima_Scadenza DATE NOT NULL,
    Scadenza DATE,
    ID_Categoria INT NOT NULL,
    Email VARCHAR(255) NOT NULL,
    CONSTRAINT PK_SPESA_RICORRENTE PRIMARY KEY (ID_Ricorrenza),
    CONSTRAINT FK_RICORRENTE_CATEGORIA FOREIGN KEY (ID_Categoria)
        REFERENCES CATEGORIA (ID_Categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_RICORRENTE_UTENTE FOREIGN KEY (Email)
        REFERENCES UTENTE (Email)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_RICORRENTE_IMPORTO CHECK (Importo_Previsto > 0),
    CONSTRAINT CK_RICORRENTE_FREQUENZA CHECK (Frequenza_Giorni > 0),
    CONSTRAINT CK_RICORRENTE_NOME CHECK (CHAR_LENGTH(TRIM(Nome)) > 0)
);

-- La transazione generata conserva il riferimento al modello ricorrente.
-- Il vincolo viene aggiunto dopo la creazione di SPESA_RICORRENTE perché la
-- tabella TRANSIZIONE viene definita prima nello schema.
ALTER TABLE TRANSIZIONE
    ADD CONSTRAINT FK_TRANSIZIONE_RICORRENZA
    FOREIGN KEY (ID_Ricorrenza)
    REFERENCES SPESA_RICORRENTE (ID_Ricorrenza)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

CREATE INDEX IDX_TRANSIZIONE_UTENTE_DATA ON TRANSIZIONE (Email, Data);
CREATE INDEX IDX_TRANSIZIONE_PERIODO ON TRANSIZIONE (ID_Periodo);
CREATE INDEX IDX_TRANSIZIONE_CATEGORIA ON TRANSIZIONE (ID_Categoria);
CREATE UNIQUE INDEX UQ_TRANSIZIONE_RICORRENZA_DATA
    ON TRANSIZIONE (ID_Ricorrenza, Data);
CREATE INDEX IDX_BUDGET_UTENTE_PERIODO ON BUDGET (Email, ID_Periodo);
CREATE INDEX IDX_DOCUMENTO_TRANSIZIONE ON DOCUMENTO (ID_Transizione);
CREATE INDEX IDX_RICORRENTE_EMAIL_SCADENZA ON SPESA_RICORRENTE (Email, Data_Prossima_Scadenza);
